
title: WebSocket
description: Work with WebSockets in PowerShell
url: https://websocket.powershellweb.com
permalink: pretty
palette: Konsolas
analyticsId: G-R5C30737B2
googleFont: Noto Sans
stylesheet: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
defaults: 
  - values: 
      layout: Default
